### PR TITLE
Problem: Cannot compile in latest Testnet v0.5.x

### PR DESCRIPTION
**Pull request by calvinlauco**
Solution: Resolve all compilation error

### CODE REVIEW

File: lib/src/transaction/staking/withdraw_unbonded_transaction_builder.ts [hunk 1]
```diff
@@ -1,4 +1,5 @@
 import ow from 'ow';
+import lodash from 'lodash';
```
Comment (foreseaz) [inline lib/src/transaction/staking/withdraw_unbonded_transaction_builder.ts:2]: Suggest to use `import _cloneDeep from 'lodash/cloneDeep'` to reduce bundle size.

File: lib/src/transaction/transfer/transfer_transaction_builder.ts [hunk 2]
```diff
@@ -1,4 +1,5 @@
 import ow, { NumberPredicate } from 'ow';
+import lodash from 'lodash';
```
Comment (foreseaz) [inline lib/src/transaction/transfer/transfer_transaction_builder.ts:2]: Same above.
