### PR TITLE
Problem: Cannot compile in latest Testnet v0.5.x

### PR DESCRIPTION
**Pull request by calvinlauco**
Solution: Resolve all compilation error

### CODE REVIEW

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try
